stages:
  - build
  - deploy

image: docker:latest

services:
  - docker:dind


before_script:
  - apk --no-cache add curl
  - curl -L -O https://github.com/rancher/rancher-compose/releases/download/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz
  - tar -zxf rancher-compose-linux-amd64-v0.12.5.tar.gz
  - mv rancher-compose-v0.12.5/rancher-compose /usr/bin/

docker_image:
  stage: build
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose-prod.yml up -d --build
    - docker-compose push

deploy_release:
  stage: deploy
  only:
   - master
  script:
   - rancher-compose up -d --pull --force-upgrade react-penca-prod
   - rancher-compose up -d --upgrade --confirm-upgrade web react-penca-prod
